name: Secrets in Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Using Secret in Application
        run: echo "Using Secret in Application"
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
