name: "Secure Workflow"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Using Secret in Application
      run: echo "Using Secret in Application"
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
